name: HuPR2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - ca-certificates=2024.2.2
  - entrypoints=0.4
  - ipykernel=5.5.5
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - ncurses=6.4.20240210
  - openssl=3.3.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - prompt-toolkit=3.0.42
  - ptyprocess=0.7.0
  - pygments=2.17.2
  - python=3.7.10
  - python_abi=3.7
  - pyzmq=24.0.1
  - readline=8.2
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.13
  - tornado=6.2
  - traitlets=5.0.0
  - wcwidth=0.1.9
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - pip:
    - addict==2.4.0
    - aliyun-python-sdk-core==2.15.1
    - aliyun-python-sdk-kms==2.16.2
    - appdirs==1.4.4
    - certifi==2024.2.2
    - cffi==1.15.1
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - crcmod==1.7
    - cryptography==42.0.5
    - cycler==0.11.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - fonttools==4.38.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - idna==3.7
    - imageio==2.31.2
    - imageio-ffmpeg==0.4.9
    - importlib-metadata==6.7.0
    - jmespath==0.10.0
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - kiwisolver==1.4.5
    - markdown==3.4.4
    - markdown-it-py==2.2.0
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - mmcv==2.0.0
    - mmengine==0.10.4
    - model-index==0.1.11
    - moviepy==1.0.3
    - natsort==8.4.0
    - nest-asyncio==1.6.0
    - numpy==1.21.6
    - opencv-python==4.9.0.80
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.0.10
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==24.0
    - pandas==1.3.5
    - pillow==9.5.0
    - platformdirs==4.0.0
    - proglog==0.1.10
    - protobuf==4.24.4
    - psutil==5.9.8
    - pycocotools==2.0.7
    - pycparser==2.21
    - pycryptodome==3.20.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2023.4
    - pyyaml==6.0.1
    - requests==2.28.2
    - rich==13.7.1
    - scipy==1.7.3
    - sentry-sdk==2.0.1
    - setproctitle==1.3.3
    - setuptools==60.2.0
    - shapely==2.0.4
    - smmap==5.0.1
    - tabulate==0.9.0
    - termcolor==2.3.0
    - terminaltables==3.1.10
    - tomli==2.0.1
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.65.2
    - typing-extensions==4.7.1
    - urllib3==1.26.18
    - wandb==0.16.6
    - yapf==0.40.2
    - zipp==3.15.0
